# Generated by Django 4.1.2 on 2022-10-07 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0002_place_place_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='place',
            name='place_id',
        ),
        migrations.AddField(
            model_name='image',
            name='position',
            field=models.IntegerField(default=0),
        ),
    ]
