# Generated by Django 4.1.2 on 2022-10-11 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0008_alter_place_description_short'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='coordinate_lat',
            field=models.DecimalField(decimal_places=14, max_digits=16),
        ),
        migrations.AlterField(
            model_name='place',
            name='coordinate_lng',
            field=models.DecimalField(decimal_places=14, max_digits=16),
        ),
    ]
