# Generated by Django 4.1.2 on 2022-10-13 13:12

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0009_alter_place_coordinate_lat_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='lat',
            field=models.DecimalField(decimal_places=14, max_digits=16, null=True, validators=[django.core.validators.MinValueValidator(limit_value=-90), django.core.validators.MaxValueValidator(limit_value=90)]),
        ),
        migrations.AddField(
            model_name='place',
            name='lng',
            field=models.DecimalField(decimal_places=14, max_digits=17, null=True, validators=[django.core.validators.MinValueValidator(limit_value=-180), django.core.validators.MaxValueValidator(limit_value=180)]),
        ),
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(upload_to='place_images'),
        ),
    ]
