# Generated by Django 4.1.2 on 2022-10-13 13:12

from django.db import migrations


def copy_coordinates(apps, schema_editor):
    Place = apps.get_model('places', 'Place')
    for place in Place.objects.all():
        place.lng = place.coordinate_lng
        place.lat = place.coordinate_lat
        place.save()


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0010_remove_place_coordinate_lat_and_more'),
    ]

    operations = [
        migrations.RunPython(copy_coordinates)
    ]




