# Generated by Django 4.1.2 on 2022-10-08 04:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0003_remove_place_place_id_image_position'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='image',
            options={'ordering': ['position']},
        ),
    ]
